// ============================================================================
// CombatEvent.h
//
// Starshatter Wars - Unreal Engine Port
//
// Description:
//     Represents a campaign-level combat event generated by planners or
//     scripted sequences. Used for mission generation, story, and campaign logic.
//
// Notes:
//     - Native (non-UObject) class
//     - UObject references must be pointers
//     - Uses legacy Text system for compatibility
//
// ============================================================================

#pragma once

#include "Types.h"
#include "Geometry.h"
#include "Text.h"
#include "List.h"
#include "GameStructs.h"
#include "Math/Vector.h"

class Campaign;
class CombatGroup;
class CombatUnit;
class UTexture2D;

// ----------------------------------------------------------------------------
// CombatEvent
// ----------------------------------------------------------------------------
class CombatEvent
{
public:
    static const char* TYPENAME() { return "CombatEvent"; }

    CombatEvent(Campaign* c,
        ECombatEventType type,
        int time,
        int team,
        ECombatEventSource source,
        const char* rgn);

    int operator==(const CombatEvent& u) const { return this == &u; }

    // ------------------------------------------------------------------------
    // Accessors
    // ------------------------------------------------------------------------
    ECombatEventType    GetType()        const { return type; }
    int                 Time()           const { return time; }
    int                 GetIFF()         const { return team; }
    const FVector&      GetPoints()      const { return points; }
    ECombatEventSource  GetSource()      const { return source; }
    FVector             Location()       const { return loc; }

    const char* Region()         const { return region; }
    const char* Title()          const { return title; }
    const char* Information()    const { return info; }
    const char* Filename()       const { return file; }
    const char* AudioFile()      const { return audio_file; }
    const char* ImageFile()      const { return image_file; }
    const char* SceneFile()      const { return scene_file; }

    UTexture2D*  GetImage()       const { return image; }
    USoundBase*  GetAudio()       const { return audio; }

    bool         Visited()        const { return visited; }

    FString GetEventSourceName() const;
    FString GetEventTypeName()   const;

    // ------------------------------------------------------------------------
    // Mutators
    // ------------------------------------------------------------------------
    void SetType(ECombatEventType t) { type = t; }
    void SetTime(int t) { time = t; }
    void SetIFF(int t) { team = t; }
    void SetPoints(const FVector& p) { points = p; }
    void SetSource(ECombatEventSource s) { source = s; }
    void SetLocation(const FVector& p) { loc = p; }

    void SetRegion(Text rgn) { region = rgn; }
    void SetTitle(Text t) { title = t; }
    void SetInformation(Text t) { info = t; }
    void SetFilename(Text f) { file = f; }
    void SetImageFile(Text f) { image_file = f; }
    void SetAudioFile(Text f) { audio_file = f; }
    void SetSceneFile(Text f) { scene_file = f; }

    void SetImage(UTexture2D* InImage) { image = InImage; }
    void SetAudio(USoundBase* InAudio) { audio = InAudio; }

    void SetVisited(bool v) { visited = v; }

    // ------------------------------------------------------------------------
    // Core
    // ------------------------------------------------------------------------
    void Load();

    // ------------------------------------------------------------------------
    // Static Helpers
    // ------------------------------------------------------------------------
    static FString GetTypeName(ECombatEventType Type);
    static ECombatEventType GetTypeFromName(const FString& Name);

    static FString GetSourceName(ECombatEventSource Source);
    static ECombatEventSource GetSourceFromName(const FString& Name);

private:
    // ------------------------------------------------------------------------
    // Core State
    // ------------------------------------------------------------------------
    Campaign* campaign = nullptr;

    ECombatEventType    type = ECombatEventType::NONE;
    int                 time = 0;
    int                 team = 0;

    ECombatEventSource  source = ECombatEventSource::NONE;
    bool                visited = false;

    // ------------------------------------------------------------------------
    // Spatial Data
    // ------------------------------------------------------------------------
    FVector             loc = FVector::ZeroVector;
    FVector             points = FVector::ZeroVector;

    // ------------------------------------------------------------------------
    // Metadata (Legacy Text System)
    // ------------------------------------------------------------------------
    Text                region;
    Text                title;
    Text                info;
    Text                file;
    Text                image_file;
    Text                audio_file;
    Text                scene_file;

    // ------------------------------------------------------------------------
    // Unreal Assets
    // ------------------------------------------------------------------------
    UTexture2D* image = nullptr;
	USoundBase* audio = nullptr;
};